### POST request to create patient
POST http://localhost:4004/api/patients
Content-Type: application/json
Authorization: Bearer {{token}}

{
   "name": "Bruce Wayne 5",
   "email": "brucewayne5@example.com",
   "address": "41st Street",
   "dateOfBirth": "1997-09-08",
   "registeredDate": "2025-03-03"
}

###